name: ionstats_env
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
 - python=3.9
 - numpy=1.25.*
 - pandas=2.1*
 - scipy=1.11.*
 - pysam=0.23*
 - meme=5.5.8
 - pip
 - pip:
      - uncalled4
      - PyYAML
