analyses:
 - preprocess
 - read_level_values
 - collect
 - stats
 - test
 - motif_discovery
run_id: IonStats_run
tests:
 - ks
 - cvm
# Data arguments
control: null
treatment: null
bam_path: null
read_path: null
summary_path: null
out_path: null
ref_path: null
data_types:
 - qs
 - sig_mean
 - sig_std
 - sig_dt
# Collector arguments
strand: both
k: 9
ref_name: null
n_vals: 65536
n_threads: 1
uc4_table_path: "resources/dna_r10.4.1_400bps_9mer.npz"
n_bins: null
save_every: null
verb: True
# Tester arguments
input_type: dict
jitter: False
js: 0.01
n_splits: 1
conversion_vals:
 - -5
 - 0.00015259021896696422
# Stat df arguments:
quantiles: True 
# Motif discovery arguments
alphabet: "resources/custom_alphabet.txt"
control_sequence_path : null
overwrite: True
# Summary reader arguments
extract_columns:
 - 'mean_qscore_template'
 - 'sequence_length_template'
 - 'barcode_rear_score'
id_column: 'barcode_arrangement'